### ISSUE TITLE
does not support malloc and free?

### ISSUE THREAD

**Issue by molixiaoge** [r-lyeh/tracey#9]
I test malloc memory leak,which can't show the leak.

**Comment by r-lyeh-archived** [comment]
I never finished the malloc/realloc/free hooks (they are specially complicated to get it to work in both /MT /MD modes on Windows, plus the CRT/DLL hell). There is a branch with some stuff already committed but it won't work for now.

 If you are on Windows try https://www.softwareverify.com/cpp-memory.php, and valgrind if you are in everything else.

**Comment by r-lyeh-archived** [comment]
Additionally, if you have access to the whole source code, considering switching all your malloc/realloc/free to tracey_malloc/tracey_realloc/tracey_free on your code. It should work.
